接入Workerman定时任务
youzan/yz-cloud-boot pull request #15
Opened 2020-01-10 03:49 UTC by xu42

2020-01-10 04:52 UTC, vimac requested changes

2020-01-10 04:52 UTC, vimac commented on bin/run.php
> +function init(): ContainerInterface
```
$container = (function():ContainerInterface { ... })();
```
只需要运行一次的代码可以这么封成匿名立即执行函数 （如同 JS

2020-01-10 04:52 UTC, vimac commented on bin/run.php
> +        if (file_exists(YZCLOUD_BOOT_APP_DIR . '/config/timing.php')) {
我建议叫 timer.php 或者 cronjob.php

2020-01-10 04:52 UTC, vimac commented on src/Daemon/Registry/TimingRegistry.php
> +        $this->beanPool[$name] = ['timeInterval' => $timeInterval, 'callback' => $callback];
不要让客户代码直面 workerman ，而是他们实现某接口，框架去调用他们接口的方法
并且，对于具体的任务，开始和结束时都加上监控性质的代码（至少加上日志），框架也可以在某种程度上维持“杀掉”那个任务的能力

2020-01-10 04:52 UTC, vimac commented on src/Daemon/Registry/TimingRegistry.php
> +        $this->beanPool[$name] = ['timeInterval' => $timeInterval, 'callback' => $callback];
另外，框架是不是应该对 timeInterval 的值做出一定的限制，避免间隔过短的任务或者过长的任务

2020-01-10 04:52 UTC, vimac commented on bin/run.php
> +$timingWorker->count = 1;
数量做成可配置吧，未来可以由客户的级别来决定

2020-01-10 04:52 UTC, vimac commented on bin/run.php
> +    $assumedAppDir = realpath(__DIR__ . '/../../../..');
这段代码如果多处调用（推定项目工程目录的），封成函数吧，不要复制粘贴

2020-01-10 04:52 UTC, vimac commented on src/Daemon/Worker/TimingWorker.php
> +            Timer::add($item['timeInterval'], $item['callback']);
这里缺乏对 $item 成员的验证，因为 $container 是全局可以访问到的，可能会被污染或者绕过框架限制加入代码

2020-01-10 05:14 UTC, xu42 commented on bin/run.php
> +$timingWorker->count = 1;
count表示进程数量，多个进程会同时执行一个任务，单进程内串行执行不同任务。为减少使用者的并发操作难度，这里指定为1。
确实可以进行自定义配置，不设置默认为1。

2020-01-10 05:54 UTC, xu42 commented on src/Daemon/Registry/TimingRegistry.php
> +        $this->beanPool[$name] = ['timeInterval' => $timeInterval, 'callback' => $callback];
使用实现接口那一套(现有的扩展点实现)，比较重，现在的方案仅需开发者提供一个定时时间参数及callback方法即可，更轻量一些。

2020-01-15 14:55 UTC, vimac commented on bin/daemon.php
> +})();
这个函数必要性不大，没必要为了闭包而闭包

2020-01-15 14:55 UTC, vimac commented on boot/functions.php
> +function developServer()
developServerFix 或者 developServerHack 是更准确的描述

2020-01-15 14:55 UTC, vimac commented on boot/functions.php
> +function developServer()
或者把动词提到最前面？ (fixDeveloperServer..?

2020-02-12 04:05 UTC, vimac commented
暂时关闭

2020-02-12 04:05 UTC, closed without merging